
logpath="log/"          #директория где логи лежат

display=20              #шаг в секундах вывода на экран
cycle=10                #шаг в секундах опроса датчиков
ip="192.168.115.0"      #все в подсети наши устройства
port=1024               #порт по которому обмен между всеми
